import {cpu, lapi, Phone} from "../../assets/images";

import {v4 as uuid} from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    brand: "Apple",
    name: "i Phone 13 Max pro",
    price: 13000,
    discountedPrice: 12000,
    img: Phone,
    category: "Phones",
    rating: 5,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "Acer",
    name: "Acer Strix 5",
    price: 18999,
    discountedPrice: 9880,
    img: lapi,
    category: "Gaming_Laptops",
    rating: 4,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "Apple",
    name: "i Phone 12 Max pro",
    price: 10000,
    discountedPrice: 8000,
    img: Phone,
    category: "Phones",
    rating: 5,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "ASUS",
    name: "ASUS CPU",
    price: 25099,
    discountedPrice: 22699,
    img: cpu,
    category: "CPU",
    rating: 4,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "Acer",
    name: "Nitro 5",
    price: 4999,
    discountedPrice: 4999,
    img: lapi,
    category: "Gaming_Laptops",
    rating: 5,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "Microsoft",
    name: "i9 intel 12th gen CPU",
    price: 13899,
    discountedPrice: 12999,
    img: cpu,
    category: "CPU",
    rating: 3,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "lenovo",
    name: "HP Pavilion Laptop",
    price: 7893,
    discountedPrice: 3898,
    img: lapi,
    category: "Laptop",
    rating: 5,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "Apple",
    name: "Mac Book pro",
    price: 11199,
    discountedPrice: 10129,
    img: lapi,
    category: "Laptop",
    rating: 4,
    quantity: 1,
    available: 5,
  },
];
