import {cpu, lapi, Phone} from "../../assets/images";

import {v4 as uuid} from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    brand: "Apple",
    name: "i Phone 13 Max pro",
    price: 13000,
    discount: 30,
    img: Phone,
    category: "phones",
    rating: 5,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "Acer",
    name: "Acer Strix 5",
    price: 18999,
    discount: 40,
    img: lapi,
    category: "gaming_laptops",
    rating: 4,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "Apple",
    name: "i Phone 12 Max pro",
    price: 10000,
    discount: 50,
    img: Phone,
    category: "phones",
    rating: 5,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "ASUS",
    name: "ASUS CPU",
    price: 25099,
    discount: 40,
    img: cpu,
    category: "cpu",
    rating: 4,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "Acer",
    name: "Nitro 5",
    price: 4999,
    discount: 50,
    img: lapi,
    category: "gaming_laptops",
    rating: 5,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "Microsoft",
    name: "i9 intel 12th gen CPU",
    price: 13899,
    discount: 50,
    img: cpu,
    category: "cpu",
    rating: 3,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "lenovo",
    name: "HP Pavilion Laptop",
    price: 7893,
    discount: 30,
    img: lapi,
    category: "laptop",
    rating: 5,
    quantity: 1,
    available: 5,
  },
  {
    _id: uuid(),
    brand: "Apple",
    name: "Mac Book pro",
    price: 11199,
    discount: 40,
    img: lapi,
    category: "laptop",
    rating: 4,
    quantity: 1,
    available: 5,
  },
];
